/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;
public class App {
    public String getGreeting() {
           return "Hello world.";
    }
    public static void main(String[] args) {
        double num1=5;
        double num2=10;
        double sum=num1+num2;
        System.out.printf("The sum of %.2f and %.2f is %.2f%n",num1,num2,sum);
       }
}
